jobs:
  build:
    environment:
      GCLOUD_PROJECT_NAME: garage-gigs
      GCLOUD_CLUSTER_NAME: cluster-1
      GCLOUD_COMPUTE_ZONE: us-east1-d
      DOCKER_IMAGE_NAME: gcr.io/garage-gigs/circleci-node-mongo
    docker:
     - image: circleci/node:7.9

    #  - image: mongo:3.5.5
    #    command: [mongod, --smallfiles]

    working_directory: ~/code

    steps:
      # and can access mongo on localhost
      # - run: sleep 5 && nc -vz localhost 27017
      - run: mkdir -p ~/code
      - checkout
      # - run: npm install --depth=0
      # - run: npm test
      # # - store_artifacts:
      # #     path: ~/code/artifacts
      - add_ssh_keys
      - setup_remote_docker
      - deploy:
          name: Maybe Deploy
          command: |
            bash .circleci/setup-gcloud.sh
            bash .circleci/gcr-upload.sh
            # docker images
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Current Branch is MASTER"
            fi
