jobs:
  build:
    environment:
      GCLOUD_PROJECT_NAME: garage-gigs
      GCLOUD_CLUSTER_NAME: gigs-1
      GCLOUD_COMPUTE_ZONE: us-east1-d
      K8S_CONTAINER: circleci-node-mongo
      K8S_NAMESPACE: staging
      DOCKER_IMAGE_NAME: gcr.io/garage-gigs/circleci-node-mongo
      GCLOUD_SERVICE_KEY: ew0KICAidHlwZSI6ICJzZXJ2aWNlX2FjY291bnQiLA0KICAicHJvamVjdF9pZCI6ICJnYXJhZ2UtZ2lncyIsDQogICJwcml2YXRlX2tleV9pZCI6ICI2MzU2Njc1MzMwMjNiOGQ4M2U5ZjkwN2E0MTk4Y2NmMjc0MzJlZmU4IiwNCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDdyt0MUZGRERIczBIMFxuOHhtYXMwWGxybUwva2s1c1hQTUtuL2VhVzBQTlNReVMvVHF2QlFBbVBreDNjOEkwUjhKN1lPRGNRRDBWSDRMZFxuYWwreEFsTVBiVEF0c0Y1UTF0TnJwUWZWaG5KZW15dXdzT2VSS2Zwb3ZNTGlxS3pHOW53RG1QdzVabmJtanl1TlxuaDBETmRFQmJEWVNNUEY3RGM0cHp3ckYrbTA0OFNJSEIybFlmQ2x3Z3pvQTR0dEI0OWxrWHpmU1RVTmJvUnpHWlxuZU1ZaW93Z0hsQnFMUG9iVWd0bVY3U0ZNRkxaQVdEQUVKOHVCSVZvNVNDZEdxcFJFQ3hERXlZVG55YlZwQWpqMlxuMDdtWHU4N0Jyb0NIeVdNWHMzUkQyYUhUV3N5SjBIa3EyYW5HVGlWRjI0YWJLT1hYdE5WU1Jlcyt4azFVeFBpbVxuWGNSWjhMNlpBZ01CQUFFQ2dnRUFjTmwxMEQrQW4wWVpiNVMzcGVKY1ZvbHRET1FBNTY0Wk41UXJNUnl5emlxZlxuUHZjRHZXZ2w0VHptUzJEZjI3QktQWnZYcGZtOE9VVGZrRW5zL0pTcjIvRld3RHR1MklNelNyZHZtR0xqZUpuZlxuTVFxTWpnN0RZcGZDZVA3dk5Pc2t4cko5V2lpUTlwRWlSMXVRSWJIWCszZFNKbzIwSzFMNFhMb3ZyYmhnR2FWZFxuWTdJdXRrbndDdzBqWDdCRDhsNk83R1FJQ1RzcFhLTXRTbUtiS3M1SFUxNm1RbmxaVWp2VjNLTTFxbTI2RytnOVxuS1VZLzRmWm1yWnVkQkxjR3pVKzZLNFpLUFNIbERkMnRPSXlQTmFoL2Nqbm85R0FVZ0Jxczd4TDEvUVBkYW53bVxuUjVNR0FSZGI4YXdZZUJRQXRIMUl6Ukd0dGpMUHRoYXlZQTNHYm4wbjFRS0JnUURycWkzUzFZdERBKzU1aGxQRVxuOFNTTWp6MzRGOTdIeVdDZGR6di9kMlo0ZS8vUWJoOVNLTUdHTWFnRmdmOCtOMThQYVNwT2d4b2tjVERFL2tuU1xua1NDVTlVRGVMVVB5dVhDNzRyb2MvSVVvVHY0L1Q5UWtvVjZkcDFPcmlmUzBEK1J1Uk1NTndnOTdXZVR4UHNTRVxuSm96d2lDdHFKNXBKNVFXRVlISGZjTnRHQXdLQmdRREFRRmRLbG9QT2xYSTZIUSszRVRxalJOaUVBYVFMTUdTdVxuM3M4YTBjWElXcG9YMWpqSWVjOFBSNTQvRHg4amVVcWZEak1hSjJVNDIxZjNkaDdoWkkrZEQ2Ym5LbUg0bnVhdFxuS1FQK21NQ3JMRC9ZOEppSW5kTWh5cGtCNkd6R3hYN0dPTU5kbVJGa2JaUEIrY0VZRXB2SXF6emNPKzVSb3IwQlxuejJIVjJlTkVNd0tCZ1FDQlFUaWEzNmJmSGNQcGdXUm1xMEE1bThNSVZNZEsyc2VUOWpiQkdsTG9tRklwbG95MVxuT2tkU2U5L0ZEWlRhSWZLUWVFVE5CUmtNamN5SzcxRzhIUDg2MC8wOUhxU2E5MXkrb0U4bDROYUQwamVlc0FFU1xuQ2pQajBrZVEyVHlPbWZ6WEFmM2RpT2VHNXpvcm14cWJ4SzBlckFEcjIwYkRhc3FJM1lEM1pXWE8wd0tCZ1FDTVxuWjdFWXVUcEVDcU1rekFxcElYMFl0blFHWElobzM0djRwcUxNckgxczZMWjNTQzJxUkVPem5oTjFiRjdLY28vTFxuLy92VVV3YzY4ZjZaclB1NmtzM0w0QjE5NEZjeTB5SVhQc2c3RFdaUTNQMDRPK2E2aDhFbGdhZ2pXNUx0ekZqY1xuL2FHNDNzeHo4dzhoY0h6VVR1clZNREkvaWNsd2Q1RGdISXdRT1pRZ1B3S0JnR25RWVZSSHdYd0piYkZ3QXpYUVxuY3BqMUp6R2luVHhFTTdacFg3cURqSjh4RThrOTg5dTZpMmhabThzWHZ3ZnkwQ0huRWROMklTSG1MN1hYOHJ0dVxuSlJEUmFWZzhSd29OZWdWbHI3eUdBZ3FYY3Jmb2h3QWNUb2N0dFhUYzByTUJxdWVZMkZ1a2dUMEVBbmtDbTRxblxuWWdRaTZadjU4N3Z2Qk9BR3dUSWE4emswXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLA0KICAiY2xpZW50X2VtYWlsIjogImNpcmNsZWNpQGdhcmFnZS1naWdzLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwNCiAgImNsaWVudF9pZCI6ICIxMTY3MjQzOTc1NDM5NzAzNTY1MDkiLA0KICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLA0KICAidG9rZW5fdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi90b2tlbiIsDQogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwNCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvY2lyY2xlY2klNDBnYXJhZ2UtZ2lncy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSINCn0=
    docker:
     - image: circleci/node:7.9

     - image: mongo:3.5.5
       command: [mongod, --smallfiles]

    working_directory: ~/code

    steps:
      # and can access mongo on localhost
      - run: sleep 5 && nc -vz localhost 27017
      - run: mkdir -p ~/code
      - checkout
      - run: npm install --depth=0
      - run: npm test
      # # - store_artifacts:
      # #     path: ~/code/artifacts
      - add_ssh_keys
      - setup_remote_docker
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              bash .circleci/setup-gcloud.sh
              bash .circleci/gcr-upload.sh
              bash .circleci/k8s-deploy-staging.sh
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash .circleci/setup-gcloud.sh
              bash .circleci/gcr-upload.sh
              # bash .circleci/k8s-deploy-production.sh
            fi
