jobs:
  build:
    docker:
     - image: circleci/node:7.9

    #  - image: mongo:3.5.5
    #    command: [mongod, --smallfiles]

    working_directory: ~/code

    steps:
      # and can access mongo on localhost
      # - run: sleep 5 && nc -vz localhost 27017
      - run: mkdir -p ~/code
      - checkout
      # - run: npm install --depth=0
      # - run: npm test
      # # - store_artifacts:
      # #     path: ~/code/artifacts
      - add_ssh_keys
      - setup_remote_docker
      # - run: bash .circleci/setup-gcloud.sh
      # - run: bash ./.circleci/setup-gcloud.sh
      # - run: ls ./.circleci
      # - run: echo $(pwd)
      # - run: ls -la
      - deploy:
          name: Maybe Deploy
          command: |
            bash .circleci/setup-gcloud.sh
            # bash .circleci/deploy.sh
            docker build --build-arg NPM_TOKEN=${NPM_TOKEN} -t gcr.io/my-project/foo-service:$(git rev-parse --short HEAD) .
          # command: |
          #   # Test gcloud
          #   bash .circleci/deploy.sh
          #   # gcloud info
          #   # echo "Hello World"
